### ISSUE TITLE
Admin login

### ISSUE THREAD

**Issue by ssundarofficial** [khalifemubin/ClassAttendance#1]
What's the admin login password?

**Comment by khalifemubin** [comment]
Hi ssundarofficial,

The login can be whatever you want. It's stored in database. If you look at
the code (ajax-service.php), it's coming from admin_master table.
The intention of this project is to put a prototype out to the world for
people like you to modify it and make it better.

Hope this helps.

Regards,
Mubin

**Comment by kelcom13** [comment]
I cant seem to login the user password is encrypted. Could you kindly state the password Thank you
